### ISSUE TITLE
Hilfecommands im Twitchchat einfügen

### ISSUE THREAD

**Issue by philimnorden** [philimnorden/TwitchPlaysEverything#3]
Der Bot soll mit entsprechenden Informationen auf Chatnachrichten wie /help oder !help antworten. Mögliche Commands wären:
- help
- commands
- github
- license
- about
- ...

**Comment by Pumpitx** [comment]
Momentane Chat Comands **eingebaut**, aber Texte fehlen noch.

**Comment by Pumpitx** [comment]
Comands eingefügt und getestet. Besitzen nun alle einen Text und Sinn.
