### ISSUE TITLE
Senden von Nachrichten über Bot an Chat

### ISSUE THREAD

**Issue by Pumpitx** [philimnorden/TwitchPlaysEverything#6]
Es sollte möglich sein, dass ich mit dem ChatBot Nachrichten an den Chat senden kann.

_Anmerkung:_
Die Funktion ist in einfach Form bereits enthalten, funktioniert aber noch nicht und sollte möglichst überarbeitet werden.

**Comment by philimnorden** [comment]
Der Bot soll 24/7 auf einem Server laufen. Dort fummelt man normalerweiße nicht rum und chattet. Wenn du Nachrichten an den Chat schicken willst, benutze doch einfach deinen normalen Account im normalen Chat. Dein Account hätte auf dem Channel ja meist auch Broadcaster/Mod-Rechte

**Comment by Pumpitx** [comment]
:(
