### ISSUE TITLE
Extrem trollende Spieler ausschließen

### ISSUE THREAD

**Issue by Pumpitx** [philimnorden/TwitchPlaysEverything#7]
Man sollte die Spieler, welche zu sehr trollen und den Bot missbrauchen, von den Funktionen ausschließen. 
Ich habe mir die Realisierung über eine eigene SQLite-Datenbank im lokalen Pfad mit dem Bot vorgestellt.

Sobald der Spieler einen Befehl eingibt wird aus der SQLite-Datenbank abgefragt, ob dieser Spieler im Chat für den Bot gesperrt ist.

Performance technisch müsste es schnell gehen, da in der Datenbank nur die gebannten Spieler drin stehen und nicht alle.

**Comment by philimnorden** [comment]
Twitch Plays ... ist keine einfach zu trollende Plattform und nicht besonders befriedigend für Trolls. Außerdem lebt die Idee von der Auseinandersetzung der Spieler und dem Streit um den nächsten Schritt im Spielablauf. Spieler sollten also nicht einfach so ausgeschlossen werden.

Anders sind Beleidigungen und ASCI-Art etc. zu werten. Dafür gibts genug Bots. Das wird hier nicht implementiert.

**Comment by Pumpitx** [comment]
:(
